name: Add new issue/PR to project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue or PR to project
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: vidavidorra/github-app-token@v1.0.0
        with:
          appId: ${{ secrets.INTERNAL_GH_APP_ID }}
          privateKey: ${{ secrets.INTERNAL_GH_APP_SECRET }}
      - name: Add to Project
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        uses: actions/add-to-project@a9f041ddd462ed185893ea1024cec954f50dbe42
        with:
          project-url: https://github.com/orgs/platformatic/projects/1
          github-token: ${{ env.TOKEN }}
